name: orofacial_filler_biofilm
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - networkx
  - seaborn
  - biopython
  - seqkit
  - ncbi-datasets-cli
  - blast
  - diamond
  - hmmer
  - quast
  - busco
  - prokka
  - bakta
  - abricate
  - ncbi-amrfinderplus
  - r-base
  - r-tidyverse
  - r-pheatmap
  - r-igraph
  - r-vegan
